# Generated by Django 3.2.9 on 2023-01-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbc',
            name='crp',
        ),
    ]
