# Generated by Django 3.2.9 on 2023-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_remove_cbc_crp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbc',
            name='bloodGroup',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='wbc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
