# Generated by Django 3.2.9 on 2023-01-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_auto_20230122_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='coagulation',
            name='act',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
