# Generated by Django 3.2.9 on 2023-01-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_coagulation_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biochemistry',
            name='troponine',
        ),
    ]
