# Generated by Django 3.2.9 on 2023-01-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_remove_biochemistry_troponine'),
    ]

    operations = [
        migrations.AddField(
            model_name='biochemistry',
            name='aslo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistry',
            name='crp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistry',
            name='rf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
