# Generated by Django 3.2.9 on 2023-01-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_electrolytes_phosphorus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serology',
            name='p_dimer',
        ),
        migrations.RemoveField(
            model_name='serology',
            name='t3',
        ),
        migrations.RemoveField(
            model_name='serology',
            name='t4',
        ),
        migrations.RemoveField(
            model_name='serology',
            name='troponine',
        ),
        migrations.RemoveField(
            model_name='serology',
            name='tsh',
        ),
    ]
