# Generated by Django 3.2.9 on 2023-01-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_auto_20230122_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serology',
            name='hcv_Ag',
        ),
        migrations.AddField(
            model_name='serology',
            name='fob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serology',
            name='hcv',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='serology',
            name='widal_h',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='serology',
            name='widal_o',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='serology',
            name='wrigh_a',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='serology',
            name='wrigh_b',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='serology',
            name='hbs_Ag',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='serology',
            name='hcg',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='serology',
            name='hiv',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
