# Generated by Django 3.2.9 on 2023-01-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_auto_20230122_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urineanalysis',
            name='amylase',
        ),
        migrations.RemoveField(
            model_name='urineanalysis',
            name='bilirubin',
        ),
        migrations.RemoveField(
            model_name='urineanalysis',
            name='creatinine',
        ),
        migrations.RemoveField(
            model_name='urineanalysis',
            name='k',
        ),
        migrations.RemoveField(
            model_name='urineanalysis',
            name='na',
        ),
    ]
