# Generated by Django 3.2.9 on 2023-01-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_auto_20230122_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='csf',
            name='appearance',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
