# Generated by Django 3.2.9 on 2023-01-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('laboratory', '0012_csf_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hormones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hba1c', models.FloatField(blank=True, null=True)),
                ('tsh', models.FloatField(blank=True, null=True)),
                ('ft4', models.FloatField(blank=True, null=True)),
                ('t4', models.FloatField(blank=True, null=True)),
                ('t3', models.FloatField(blank=True, null=True)),
                ('lh', models.FloatField(blank=True, null=True)),
                ('fsh', models.FloatField(blank=True, null=True)),
                ('prolactin', models.FloatField(blank=True, null=True)),
                ('testosterone', models.FloatField(blank=True, null=True)),
                ('cortisol', models.FloatField(blank=True, null=True)),
                ('vit_d', models.FloatField(blank=True, null=True)),
                ('ferritin', models.FloatField(blank=True, null=True)),
                ('d_dimer', models.FloatField(blank=True, null=True)),
                ('b_hcg', models.FloatField(blank=True, null=True)),
                ('troponin_i', models.FloatField(blank=True, null=True)),
                ('troponin_t', models.FloatField(blank=True, null=True)),
                ('amh', models.FloatField(blank=True, null=True)),
                ('psa', models.FloatField(blank=True, null=True)),
                ('cea', models.FloatField(blank=True, null=True)),
                ('afp', models.FloatField(blank=True, null=True)),
                ('toxo_igg_igm', models.FloatField(blank=True, null=True)),
                ('recorder', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
    ]
