# Generated by Django 3.2.9 on 2022-12-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathology', models.TextField(blank=True, null=True)),
                ('laboratory', models.TextField(blank=True, null=True)),
                ('radiological', models.TextField(blank=True, null=True)),
                ('surgical', models.TextField(blank=True, null=True)),
                ('medicine', models.CharField(blank=True, max_length=30, null=True)),
                ('recommendations', models.CharField(blank=True, max_length=25, null=True)),
                ('leaveDate', models.DateTimeField(auto_now_add=True)),
                ('leavingDepartment', models.CharField(blank=True, max_length=20, null=True)),
                ('dischargeStatus', models.CharField(blank=True, max_length=35, null=True)),
                ('operator', models.CharField(max_length=20, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
    ]
