# Generated by Django 3.2.9 on 2022-12-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('age', models.FloatField(blank=True, default=0, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('marriage', models.CharField(default='', max_length=20, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ses', models.BooleanField(default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('operator', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(default=1, null=True)),
                ('count', models.SmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('polyclinicDepartment', models.CharField(blank=True, max_length=27, null=True)),
                ('patientID', models.CharField(default='', max_length=11)),
                ('enterDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('condition', models.SmallIntegerField(blank=True, null=True)),
                ('haveSes', models.BooleanField(blank=True, default=True, null=True)),
                ('transferDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('haveLaboratoryTest', models.SmallIntegerField(default=0)),
                ('haveXRayTest', models.SmallIntegerField(default=0)),
                ('arrive', models.BooleanField(default=False, null=True)),
                ('arriveDate', models.DateTimeField(blank=True, null=True)),
                ('typeOfEmergency', models.SmallIntegerField(default=0, null=True)),
                ('operator', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('basicInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.basicinfo')),
                ('sickroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.ward')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True)),
                ('medicalHistory', models.TextField(blank=True)),
                ('surgeryHistory', models.TextField(blank=True)),
                ('medicineHistory', models.TextField(blank=True)),
                ('allergyHistory', models.TextField(blank=True)),
                ('familyHistory', models.TextField(blank=True)),
                ('habit', models.TextField(blank=True)),
                ('clinicalExamination', models.TextField(blank=True)),
                ('test', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('remind', models.TextField(blank=True)),
                ('doctor', models.CharField(default='', max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('consultation', models.TextField(blank=True)),
                ('isOpen', models.SmallIntegerField(default=0)),
                ('openDate', models.DateTimeField()),
                ('closeDate', models.DateTimeField(null=True)),
                ('opener', models.CharField(default='', max_length=25)),
                ('writer', models.CharField(default='', max_length=25)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
    ]
