# Generated by Django 3.2.9 on 2023-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_ward_arabic_name'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='department',
            field=models.ManyToManyField(blank=True, to='department.Department'),
        ),
    ]
