# Generated by Django 3.2.9 on 2023-04-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientinfo_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentpatient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentpatient',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='DepartmentPatient',
        ),
    ]
