# Generated by Django 3.2.9 on 2022-12-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('arabic_name', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('arabic_name', models.CharField(blank=True, default='', max_length=35, null=True)),
                ('account', models.SmallIntegerField(blank=True, null=True, unique=True)),
                ('password', models.CharField(max_length=11)),
                ('sex', models.CharField(max_length=6)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('currentTemplateUrl', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('language', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('authorityDepartment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('authorityMenu', models.ManyToManyField(blank=True, to='department.Menu')),
                ('authorityWard', models.ManyToManyField(blank=True, to='department.Ward')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.position')),
                ('template', models.ManyToManyField(blank=True, to='department.Template')),
            ],
        ),
    ]
