# Generated by Django 3.2.9 on 2022-12-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('bloodPressureMax', models.IntegerField(blank=True, null=True)),
                ('bloodPressureMin', models.IntegerField(blank=True, null=True)),
                ('bloodPressureAverage', models.IntegerField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('breathingRate', models.IntegerField(blank=True, null=True)),
                ('urineOutput', models.FloatField(blank=True, null=True)),
                ('oxygen', models.CharField(blank=True, default='', max_length=7, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(default='', max_length=20, null=True)),
                ('vt', models.IntegerField(blank=True, null=True)),
                ('fio2', models.IntegerField(blank=True, null=True)),
                ('psv', models.IntegerField(blank=True, null=True)),
                ('peep', models.IntegerField(blank=True, null=True)),
                ('recorder', models.CharField(max_length=35)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DatesInICU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('icuPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
    ]
