# Generated by Django 3.2.9 on 2022-12-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('arabic_name', models.CharField(default='', max_length=35)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('arabic_name', models.CharField(default='', max_length=35)),
                ('url_name', models.CharField(default='', max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('arabic_name', models.CharField(default='', max_length=35)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('arabic_name', models.CharField(default='', max_length=35)),
                ('url_name', models.CharField(default='', max_length=35, unique=True)),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.menucategory')),
            ],
        ),
    ]
