# Generated by Django 3.2.9 on 2023-04-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_ward_arabic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='types',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
