# Generated by Django 3.2.9 on 2023-04-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='arabic_name',
            field=models.CharField(default='', max_length=35, unique=True),
        ),
    ]
