# Generated by Django 3.2.9 on 2023-04-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_arabic_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
